ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.hkhinfoxyg.xyz
CATALOGUE_HOST: catalogue-dev.hkhinfoxyg.xyz
REDIS_HOST: redis-dev.hkhinfoxyg.xyz
USER_HOST: user-dev.hkhinfoxyg.xyz
CART_HOST: cart-dev.hkhinfoxyg.xyz
MYSQL_HOST: mysql-dev.hkhinfoxyg.xyz
SHIPPING_HOST: shipping-dev.hkhinfoxyg.xyz
RABBITMQ_HOST: rabbitmq-dev.hkhinfoxyg.xyz
PAYMENT_HOST: payment-dev.hkhinfoxyg.xyz